export * from './MoviesPage/MoviesPage'
export * from './MoviesDetailsPage/MoviesDetailsPage'
export * from './HomePage/HomePage'
export * from './GenresPage/GenresPage'
export * from './MoviesByNamePage/MoviesByNamePage'